# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ramya04
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: emailapiapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: emailapi

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    SENDER_EMAIL: chennusramyasri@gmail.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true
